"""
Export the symbol pool and alias map from the Python data module into plain JS
files that the PWA can import as ES modules.

Usage (from repo root):
    python pwa/scripts/export_data.py

Output:
    pwa/data/pool.js   — export const POOL = [...]
    pwa/data/alias.js  — export const ALIAS = [...]

Both arrays are parallel: ALIAS[i] is the alias for POOL[i].
"""

import json
import sys
from pathlib import Path

# Make sure the repo root is on sys.path so data/ imports work
REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from data.unicode_pool import SYMBOL_POOL
from data.alias_map import build_alias_map

def main():
    alias_map = build_alias_map()

    pool = SYMBOL_POOL
    alias = [alias_map[s] for s in pool]

    out_dir = REPO_ROOT / "pwa" / "data"
    out_dir.mkdir(parents=True, exist_ok=True)

    pool_js = out_dir / "pool.js"
    pool_js.write_text(
        "// AUTO-GENERATED by pwa/scripts/export_data.py — do not edit by hand\n"
        "// Source: data/unicode_pool.py\n"
        f"// Pool size: {len(pool)}\n"
        f"export const POOL = {json.dumps(pool, ensure_ascii=False)};\n",
        encoding="utf-8",
    )

    alias_js = out_dir / "alias.js"
    alias_js.write_text(
        "// AUTO-GENERATED by pwa/scripts/export_data.py — do not edit by hand\n"
        "// Source: data/alias_map.py\n"
        f"// Alias count: {len(alias)}\n"
        f"export const ALIAS = {json.dumps(alias, ensure_ascii=False)};\n",
        encoding="utf-8",
    )

    print(f"pool.js  -> {pool_js}  ({pool_js.stat().st_size // 1024} KB)")
    print(f"alias.js -> {alias_js}  ({alias_js.stat().st_size // 1024} KB)")
    print(f"Pool size: {len(pool)} symbols")


if __name__ == "__main__":
    main()
